on:
    push:
        branches: [main]
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: cache yay
              uses: actions/cache@v3
              with:
                  path: yay-cache
                  key: yay-cache

            - name: build pacman repository
              id: build
              uses: ./

            - name: create release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: 'output/*,yay-cache/**/*.tar.zst'
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ steps.build.outputs.RELEASE_TAG }}
